name: Automated deployment of hospital nuget

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

env:
  HOSPITAL-DLL-PATH : 'PharmacyLibrary/PharmacyLibrary.csproj'
  OUTPUT-DLL-DIR : '${{ github.workspace }}\output'
  NUGET-SOURCE-URL : 'https://api.nuget.org/v3/index.json'

jobs:
  deploy-nuget:
    runs-on : ubuntu-latest
    steps:
      - name : Pulling repository to the VM
        uses : actions/checkout@v2
      
      - name : Installing the dotnet tool
        uses: actions/setup-dotnet@v1
        with:
          dotnet-verison: '5.0.x'

      - name : Listing dir
        run : ls -a

      - name : Restore and build packages
        id : build-results
        run : dotnet build ${{ env.HOSPITAL-DLL-PATH }} --configuration Release


      
      - name : Packaging the dll
        run: dotnet pack ${{ env.HOSPITAL-DLL-PATH }} --no-restore --no-build --configuration Release   --output ${{ env.OUTPUT-DLL-DIR }}

      - name : Pushing to nuget repository
        run: dotnet nuget push ${{ env.OUTPUT-DLL-DIR }}/*.nupkg -k ${{ secrets.DAJANAS_TOKEN }} -s ${{ env.NUGET-SOURCE-URL }}
