name: Nuget package

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

env:
  PROJECT-DLL-PATH : 'PharmacyLibrary/PharmacyLibrary.csproj'
  OUTPUT-DLL-DIR : 'https://nuget.pkg.github.com/Dajana11-99/index.json'
  NUGET-SOURCE-URL : 'https://api.nuget.org/slack/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on : ubuntu-latest
    steps:
      - name : Pulling repository to the VM
        uses : actions/checkout@v2
      
      - name : Installing the dotnet tool
        uses: actions/setup-dotnet@v1
        with:
          dotnet-verison: '5.0.x'

      - name : Restore and build packages
        id : build-results
        run : dotnet build ${{ env.PROJECT-DLL-PATH }} --configuration Release
        
      - name : Determining the version
        id : get_version
        uses : battila7/get-version-action@v2


      

      - name : Packaging the dll
        run: dotnet pack ${{ env.PROJECT-DLL-PATH }} --no-restore --no-build --configuration Release --include-symbols   --output ${{ env.OUTPUT-DLL-DIR }}

      - name : Pushing to nuget repository
        run: dotnet nuget push ${{ env.OUTPUT-DLL-DIR }}/*.nupkg -k ${{ secrets.DAJANAS_TOKEN }} -s ${{ env.NUGET-SOURCE-URL }}
