name: Packaging Integration Library

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

env:
 PROJECT-DLL : 'PharmacyLibrary/PharmacyLibrary.csproj'
 GITHUB_TOKEN:    '${{ secrets.DAJANAS_TOKEN }}'  
 OUTPUT-DLL-DIR : '${{ github.workspace }}\output'


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Clean
      run: dotnet clean ${{ env.PROJECT-DLL }} && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: nuget restore ${{ env.PROJECT-DLL }}
    - name: Build
      run: dotnet build ${{ env.PROJECT-DLL }} --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test ${{ env.PROJECT-DLL }} --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack ${{ env.PROJECT-DLL }} --configuration Release /p:Version=${VERSION} --no-build --output ${{ env.OUTPUT-DLL-DIR }}
    - name: Push
      run: dotnet nuget push ${{ env.OUTPUT-DLL-DIR }}/*.nupkg --api-key ${GITHUB_TOKEN} --source https://nuget.pkg.github.com/magdalenaRA822018/slack/package.json 
 